### ISSUE TITLE
Integrate Security Hub

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-marketplace#132]
**As** a Buyer
**I want** Security information about packages
**So that** I can make an informed decision

## Acceptance Criteria
**Given** A user is navigating a package on UDS Marketplace 
**When** Viewing detailed information about the package/application
**Then** data provided by [uds-security-hub](https://github.com/defenseunicorns/uds-security-hub/blob/main/docs/db.md) is integrated with the tech stack and displayed to the user, per Figma design

Instructions on pulling security hub db [here](https://github.com/defenseunicorns/uds-security-hub-scanning?tab=readme-ov-file#how-to-download-and-verify-uds_security_hubdb)

```[tasklist]
- [ ] Investigate security hub integration with golang backend
- [ ] Investigate integrating security hub db with uds-marketplace zarf package
- [ ] Integrate security hub with golang backend and expose via API
```

**Comment by andrewg-xyz** [comment]
Assuming GitHub role with access to s3 bucket: https://defense-unicorns.slack.com/archives/C02UAUHK3DX/p1723746601446269?thread_ts=1722872772.949129&cid=C02UAUHK3DX

**Comment by andrewg-xyz** [comment]
Pull in Security Hub Data
- raw count of category of CVE data
- Availability of SBOM and CVE reports

**Comment by andrewg-xyz** [comment]
Related Metatdata sources: https://docs.google.com/spreadsheets/d/1ByW5NUyQe9LUYwI7qaW7kBK5Z4SuiJDWcMroKeRYblc/edit?pli=1&gid=0#gid=0
