### ISSUE TITLE
UI Review Updates

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-marketplace#155]
```[tasklist]
### Tasks
- [x] Update Spacing between Cards on Catalog View
- [x] Update Scrollbar in Catalog View
- [x] Add back in containers on App view details
- [x] Add placeholder content to tabs
```
