### ISSUE TITLE
Add empty icon state for package cards

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/uds-marketplace#184]
### Is your feature request related to a problem? Please describe.

When a package is added to marketplace with the icon value in the metadata schema empty - there needs to be a common empty state. 

In order to clearly articulate that this is an application package we will use the package icon that is common across the rest of UDS in place of an empty icon state to communicate still what the user is looking at. 

Note: In the future there will be a different icon used for pre-integrated capability bundles. 

### Describe the solution you'd like

- **Given** A user is viewing app on the catalog page or the app details page 
- **When** the application metadata is missing an icon
- **Then** show the default app icon in it's place

### Describe alternatives you've considered
Showing no icon would lead to a lot of empty states. 

### Design 
Figma file https://www.figma.com/design/1xQF8rcaVAbJXcQxXal0RS/UDS-Marketplace?node-id=5474-5469&m=dev

<img width="433" alt="App Card - state - no icon in config" src="https://github.com/user-attachments/assets/b8174560-b6b8-4e75-8739-3ea4b788dba9">

![App Logo](https://github.com/user-attachments/assets/515750b5-6483-4fe6-b3e3-42044248f4b1)

```[tasklist]
### Tasks
- [ ] Replace defaults to use this pattern
- [ ] [fix] metdata kafka-ui spec.repository
- [ ] replace bad icon with default for Bitbucket, kafka ui, strimzi, zookeepr
```
