### ISSUE TITLE
UDS Marketplace Initial Catalogue and Application Details View

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-marketplace#60]
**As** a Mission Hero 
**I want** to find software tools available that may solve my problems
**So that** I can accelerate my market research
**And** Improve accessibility of software for operational users

## Acceptance Criteria
**Given** I am a user searching for software tools
**When** I open apps.defenseunicorns.com
**Then** I see tiles or cards of software applications
**And** I see a simple way to search for keywords or phrases
**And** the displayed tiles/cards are filtered base on the searched keywords or phrases

**Given** I have opened a single application tile
**When** Viewing the application view
**Then** I see a text overview of the application
**And** I see a contracting document collapsable overview
**And** I see a contracting info button to download a pdf
**And** I see a collapsable overview of Security Information
**And** I see a security report button to download a pdf
**And** I see a section with a high level description explaining how to get this package in your environment
**And** a button to 'Talk to a Mission Expert' navigating to https://www.defenseunicorns.com/contactus

```[tasklist]
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/64
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/65
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/66
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/67
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/68
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/90
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/91
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/69
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/110
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/109
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/70
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/104
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/93
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/71
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/74
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/122
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/96
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/75
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/76
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/78
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/116
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/137
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/138
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/117
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/140
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/142
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/155
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/144
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/139
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/73
```
