### ISSUE TITLE
Supported Standardization of Application Integration

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-marketplace#61]
**As** Consumer of UDS Marketplace applications
**I want** confidence in the security and functionality of applications
**So that** I can Improve the accessibility of software for operational users

## Acceptance Criteria
**Given** An application
**When** engineering work is done to integrate with UDS
**Then** there exists defined security standards 
**And** there exists documentation for these standards
**And** there exists supporting Continuous Integration jobs to enforce these standards
**And** there is defined required metadata for the application
**And** there exists documentation for this metadata
**And** there exists supporting Continuous integration jobs to enforce these requirements
**And** there exists defined functional checkout of applications
**And** there exists documented guidelines on suggested framework/s to perform functional checkout

```[tasklist]
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/87
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/82
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/84
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/85
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/89
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/58
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/63
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/23
- [ ] https://github.com/defenseunicorns/uds-common/pull/205
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/83
- [ ] https://github.com/defenseunicorns/uds-marketplace/issues/182
```
